LUAC = "C:/Program Files (x86)/Gideros/Tools/luac.exe"

all: .tmp/scenemanager.lua.bin .tmp/button.lua.bin .tmp/socket.lua.bin .tmp/Music.lua.bin .tmp/Sounds.lua.bin .tmp/Settings.lua.bin .tmp/Config.lua.bin .tmp/easing.lua.bin .tmp/View.lua.bin .tmp/gtween.lua.bin .tmp/Ace.Slide.lua.bin .tmp/AddFunction.lua.bin .tmp/Boxes.lua.bin .tmp/BackStart.lua.bin .tmp/Boundary.lua.bin .tmp/ControlSound.lua.bin .tmp/BaffleBox.lua.bin .tmp/GameEnd.lua.bin .tmp/P2_GAMESTART.lua.bin .tmp/P1_GAMESTART.lua.bin .tmp/select.lua.bin .tmp/Ipconnect.lua.bin .tmp/options.lua.bin .tmp/Rules.lua.bin .tmp/start.lua.bin .tmp/main.lua.bin

.tmp/scenemanager.lua.bin: scenemanager.lua
	$(LUAC) -o ".tmp/scenemanager.lua.bin" "scenemanager.lua"

.tmp/button.lua.bin: button.lua
	$(LUAC) -o ".tmp/button.lua.bin" "button.lua"

.tmp/socket.lua.bin: socket.lua
	$(LUAC) -o ".tmp/socket.lua.bin" "socket.lua"

.tmp/Music.lua.bin: Music.lua
	$(LUAC) -o ".tmp/Music.lua.bin" "Music.lua"

.tmp/Sounds.lua.bin: Sounds.lua
	$(LUAC) -o ".tmp/Sounds.lua.bin" "Sounds.lua"

.tmp/Settings.lua.bin: Settings.lua
	$(LUAC) -o ".tmp/Settings.lua.bin" "Settings.lua"

.tmp/Config.lua.bin: Config.lua
	$(LUAC) -o ".tmp/Config.lua.bin" "Config.lua"

.tmp/easing.lua.bin: easing.lua
	$(LUAC) -o ".tmp/easing.lua.bin" "easing.lua"

.tmp/View.lua.bin: View.lua
	$(LUAC) -o ".tmp/View.lua.bin" "View.lua"

.tmp/gtween.lua.bin: gtween.lua
	$(LUAC) -o ".tmp/gtween.lua.bin" "gtween.lua"

.tmp/Ace.Slide.lua.bin: Ace.Slide.lua
	$(LUAC) -o ".tmp/Ace.Slide.lua.bin" "Ace.Slide.lua"

.tmp/AddFunction.lua.bin: AddFunction.lua
	$(LUAC) -o ".tmp/AddFunction.lua.bin" "AddFunction.lua"

.tmp/Boxes.lua.bin: Boxes.lua
	$(LUAC) -o ".tmp/Boxes.lua.bin" "Boxes.lua"

.tmp/BackStart.lua.bin: BackStart.lua
	$(LUAC) -o ".tmp/BackStart.lua.bin" "BackStart.lua"

.tmp/Boundary.lua.bin: Boundary.lua
	$(LUAC) -o ".tmp/Boundary.lua.bin" "Boundary.lua"

.tmp/ControlSound.lua.bin: ControlSound.lua
	$(LUAC) -o ".tmp/ControlSound.lua.bin" "ControlSound.lua"

.tmp/BaffleBox.lua.bin: BaffleBox.lua
	$(LUAC) -o ".tmp/BaffleBox.lua.bin" "BaffleBox.lua"

.tmp/GameEnd.lua.bin: GameEnd.lua
	$(LUAC) -o ".tmp/GameEnd.lua.bin" "GameEnd.lua"

.tmp/P2_GAMESTART.lua.bin: P2_GAMESTART.lua
	$(LUAC) -o ".tmp/P2_GAMESTART.lua.bin" "P2_GAMESTART.lua"

.tmp/P1_GAMESTART.lua.bin: P1_GAMESTART.lua
	$(LUAC) -o ".tmp/P1_GAMESTART.lua.bin" "P1_GAMESTART.lua"

.tmp/select.lua.bin: select.lua
	$(LUAC) -o ".tmp/select.lua.bin" "select.lua"

.tmp/Ipconnect.lua.bin: Ipconnect.lua
	$(LUAC) -o ".tmp/Ipconnect.lua.bin" "Ipconnect.lua"

.tmp/options.lua.bin: options.lua
	$(LUAC) -o ".tmp/options.lua.bin" "options.lua"

.tmp/Rules.lua.bin: Rules.lua
	$(LUAC) -o ".tmp/Rules.lua.bin" "Rules.lua"

.tmp/start.lua.bin: start.lua
	$(LUAC) -o ".tmp/start.lua.bin" "start.lua"

.tmp/main.lua.bin: main.lua
	$(LUAC) -o ".tmp/main.lua.bin" "main.lua"

